version: "3.9"

volumes:
  db-data:
    driver: local
  metabase-data:
    driver: local

services:
  go_app1:
    container_name: go_app1
    build:
      context: .
      dockerfile: "./docker/golang/Dockerfile"
    volumes:
      - "./go_app1/:/go/src/app1"
    depends_on:
      - db
    tty: true
    stdin_open: true
  metabase:
    image: metabase/metabase
    container_name: "metabase"
    volumes:
      - "metabase-data:/metabase-data"
    # environment:
    #   # MB_DB_FILE: /metabase-data/metabase.db
    #   MB_DB_TYPE: postgres
    #   MB_DB_DBNAME: metabase
    #   MB_DB_PORT: 5432
    #   MB_DB_USER: postgres
    #   # MB_DB_PASS: metabase
    #   MB_DB_PASS: postgres
    #   # MB_DB_HOST: db
    ports:
      - "4649:3000"
    depends_on:
      - db
    platform: linux/amd64
    
  db:
    image: postgres:14-alpine
    container_name: "metabase-db"
    ports:
      - "5432:5432"
    env_file:
      - "./docker/postgres/.env"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./docker/postgres/init:/docker-entrypoint-initdb.d"
